open_file = ["Command+O"]
switch_file = ["Command+Shift+O"]
undo = ["Command+Z", "U"]
redo = ["Command+Shift+Z", "Command+Y"]
toggle_side_panel = ["B"]
toggle_toolbar = ["T"]
goto_end = ["E"]
goto_start = ["S"]
goto_top = ["Home"]
goto_bottom = ["End"]
save_state_file = ["Command+S"]
group_new = ["G"]
item_focus = ["F"]
select_all = ["Command+A"]
select_toggle = ["A"]
reload_waveform = ["R"]
zoom_in = ["Plus", "Equals"]
zoom_out = ["Minus"]
ui_zoom_in = ["Command+Plus"]
ui_zoom_out = ["Command+Minus"]
scroll_up = ["PageUp"]
scroll_down = ["PageDown"]
delete_selected = ["Delete", "X"]
marker_add = ["M"]
toggle_menu = ["Alt+M"]
show_command_prompt = ["Space"]
